### ISSUE TITLE
No confetti when Windows animations are disabled

### ISSUE THREAD

**Issue by gutnar** [Mitcheljager/svelte-confetti#9]
Currently the library decides that the confetti should not be displayed at all when `prefers-reduced-motion` media selector goes through. I think this decision should be left to the users of the library instead. The main problem is that Windows has this one setting to disable animations that affects a very large set of features and this library not working is quite unexpected behavior in that case.

```css
@media (prefers-reduced-motion) {
  .confetti,
  .confetti::before {
    animation: none;
  }
}
```
